apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: katie-paper-gateway
  namespace: katie-paper
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: minecraft
      protocol: TCP
      port: 33333