apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: katie-paper-route
  namespace: katie-paper
spec:
  parentRefs:
    - name: katie-paper-gateway
  rules:
    - backendRefs:
        - name: katie-paper
          port: 25565